name: Build and Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Start the Build
      run: echo "Building and testing ${{ github.event.pull_request.head.sha }}"
    
    - name: Checkout PR Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
